services:
  - type: web
    name: your-app-name
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn nacos_allocation.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"