# Generated by Django 5.2.6 on 2025-09-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
