# Generated by Django 5.2.6 on 2025-09-08 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_user_managers'),
        ('supervisors', '0002_supervisor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='frontend.department'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='supervisor',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='unique_supervisor_name_per_department'),
        ),
        migrations.AddConstraint(
            model_name='supervisor',
            constraint=models.UniqueConstraint(fields=('department', 'email'), name='unique_supervisor_email_per_department'),
        ),
    ]
