# Generated by Django 5.2.6 on 2025-09-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_user_managers'),
        ('supervisors', '0003_supervisor_department_alter_supervisor_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supervisor',
            name='unique_supervisor_email_per_department',
        ),
        migrations.AddConstraint(
            model_name='supervisor',
            constraint=models.UniqueConstraint(condition=models.Q(('email', None), _negated=True), fields=('department', 'email'), name='unique_supervisor_email_per_department'),
        ),
    ]
