# Generated by Django 5.2.6 on 2025-09-06 16:32

import frontend.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', frontend.managers.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='secret_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='secret_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_department_admin', True)), fields=('department',), name='unique_department_admin'),
        ),
    ]
