# Generated by Django 5.2.6 on 2025-09-05 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('supervisors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=50)),
                ('num_groups', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='allocation.allocationresult')),
                ('students', models.ManyToManyField(blank=True, to='students.student')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisors.supervisor')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('number', 'supervisor', 'allocation_result')},
            },
        ),
    ]
