# Generated by Django 5.2.6 on 2025-09-06 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
        ('frontend', '0002_alter_user_options_alter_user_managers_and_more'),
        ('students', '0002_student_department'),
        ('supervisors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='frontend.department'),
        ),
        migrations.RemoveField(
            model_name='group',
            name='students',
        ),
        migrations.AlterField(
            model_name='group',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='supervisors.supervisor'),
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='students.student'),
        ),
    ]
