# Generated by Django 5.2.6 on 2025-09-06 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_group_department_remove_group_students_and_more'),
        ('students', '0002_student_department'),
        ('supervisors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='students',
        ),
        migrations.AlterField(
            model_name='group',
            name='supervisor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='supervisors.supervisor'),
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='groups', to='students.student'),
        ),
    ]
